export { default as About } from './About';
export { default as Background } from './Background';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as Home } from './Home';
export { default as Mouse } from './Mouse';
export { default as Navbar } from './Navbar';
export { default as Proyect } from './Proyect';
export { default as Proyects } from './Proyects';
export { default as Skills } from './Skills';
export * from './firebase';
export { default as wrapper } from './wrapper';
